export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT"

export const OPEN_SNACKBAR = "OPEN_SNACKBAR"
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"

export const GET_ALL_BLOGS_REQUEST = "GET_ALL_BLOGS_REQUEST"
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS"
export const GET_ALL_BLOGS_ERROR = "GET_ALL_BLOGS_ERROR"

export const LIKE_BLOG = "LIKE_BLOG"
export const UNLIKE_BLOG = "UNLIKE_BLOG"

export const POST_BLOG = "POST_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const EDIT_BLOG = "EDIT_BLOG"

export const GET_MY_BLOGS_REQUEST = "GET_MY_BLOGS_REQUEST"
export const GET_MY_BLOGS_SUCCESS = "GET_MY_BLOGS_SUCCESS"
export const GET_MY_BLOGS_ERROR = "GET_MY_BLOGS_ERROR"
